### ISSUE TITLE
Readme suggestion - more installation / getting started help

### ISSUE THREAD

**Issue by toddmo** [Mathics3/mathics-django#160]
In order to get this installed, first I had to run:

`sudo apt-get install python-dev default-libmysqlclient-dev`

Then I could run the command from the package page (https://pypi.org/project/Mathics-omnibus/):

`pip install Mathics-omnibus`

Before I did that, it was getting an error about sql-client.

---

After I got this installed, after much guesswork, the way I got this to run was by:

` /home/toddmo/.local/bin/mathicsserver`

After which I could finally get to 

`http://localhost:8000`

---

My ask is that most or all of this information be included explicitly in the readme. It would have saved me an hour. It may save lots of people a significant amount of time. There are new installation platforms and application platforms intruduced into our environments almost on a weekly basis. The assumption should be a first time user for such platforms. It seems like half of all software I ever installed was with a new, different installation system. Which is fine I guess, but it means users probably need a bit more explicit help. Thanks!

**Comment by rocky** [comment]
I am sorry you had such a hard time getting this working, but I am glad you didn't give up and got it installed. 

Writing installation instructions for something this complex is not easy. Your instructions are a bit specific to your setup. For example it assumes a Debian or Ubuntu installation. 

And it might not be complete for someone else running either of these OS's since they may or may not have other needed packages that you might have installed. (Or it may be that your installation is not fully complete). 

That said, I have made an effort to revise instructions for Mathics-core. See https://github.com/Mathics3/mathics-django/pull/161 and https://mathics-development-guide.readthedocs.io/en/latest/installing.html 

Freel free to review these and make suggestions in the form of Pull Requests (PR)s.
