### ISSUE TITLE
Several failures during tests

### ISSUE THREAD

**Issue by thierry-FreeBSD** [Mathics3/mathics-django#19]
The tests, launched with py.test, produce several errors caused by missing modules.
Actually, they exist, but they belong to mathics_scanner and no more to mathics.core.
The attached patch fixes that.
[patch-mathics-django-2.0.0_tests.txt](https://github.com/Mathics3/mathics-django/files/5990224/patch-mathics-django-2.0.0_tests.txt)

**Comment by rocky** [comment]
Thanks for the information and patches.

Hmm - all of these tests were a holdover from copying from Mathics. We test this over there and that is the place where this should be tested. 

Not here. https://github.com/Mathics3/mathics-django/pulls will remove these soon. 

(I didn't notice this since I was testing using `make check` which does the right thing here.)

By the way, there _are_ some package corrections that have gone on since the 2.0.0 release.  I will probably put in a 2.0.1 release over the weekend to pick up what is in the current master branch right now.

**Comment by rocky** [comment]
I think this was a transient situation.
