### ISSUE TITLE
Integrate[...] prints unicode F74C instead of "d" in "dx"

### ISSUE THREAD

**Issue by GarkGarcia** [Mathics3/mathics-django#4]
This is a follow up to https://github.com/mathics/Mathics/issues/206:

> I can reproduce this by opening http://www.mathics.net/ and doing:
> 
> ```
> Integrate[y[x], x]
> ```
> 
> which gives:
> 
> ```
>  ∫y[x]x
> ```

**Comment by mmatera** [comment]
The problem with this is that F74C  is not implemented in standard fonts, but just in Wolfram's. Keep this code is important for the structure, but it should be mapped to something else when it is translated to MathML or latex...

**Comment by rocky** [comment]
I have encountered something like this in mathicsscript too. See [here](https://github.com/Mathics3/mathicsscript/blob/master/mathicsscript/termshell.py#L76-L87)

Note though that it doesn't have this particular symbol, but probably should. Maybe that code should be put in Mathics (the common library code) and called in front-ends.?

**Comment by rocky** [comment]
In commit 772f295 I basically cut and pasted the workaround I have in `mathicsscript`. 

However to be fixed properly, really Mathics core should be fixed so it doesn't add such weird characters when doing the formatting. 

We should be able to note in the formatter that we want Unicode, rather than WL fonts.

And to do that each operator may need to like the one for pattern so that it knows about the unicode character as well as say `->` which it has now.
